### ISSUE TITLE
XML snippets and others

### ISSUE THREAD

**Issue by SalahAdDin** [mohamedmagdy/odoo-pycharm-templates#16]
Hi,

Thank you for your work, my main IDE is PyCharm.

I tested VSCode snippets and I think they are a few more completed because they have also `xml` snippets.

What's about this project?

Thanks.

**Comment by mohamedmagdy** [comment]
Hi,

This project contains snippets for XML and Python. I understand that it was not updated for a while which means it might miss some updates.

Anyway, It contains both XML and Python.

Best Regards,

**Comment by SalahAdDin** [comment]
I tried to do that, but in `xml` i cannot get them, but it works in python files.

**Comment by mohamedmagdy** [comment]
In Pycharm, Try `Invalidate Caches / Restart`. This would help

**Comment by SalahAdDin** [comment]
I will test it again, one moment.

**Comment by SalahAdDin** [comment]
Unfortunately, it does not work in `xml` files:
![deepin-screen-recorder_select area_20181024154808](https://user-images.githubusercontent.com/5034215/47431394-62620700-d7a4-11e8-80dc-0819e4cc3415.gif)

Working with:
PyCharm 2018.2.4 (Professional Edition)
Build #PY-182.4505.26, built on September 19, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.18.14-arch1-1-ARCH

**Comment by mohamedmagdy** [comment]
I have the same environment except for Pycharm which is:
PyCharm 2018.2.4 (**_Community_** Edition)

Also, I never tested it with Professional Edition!
I believe this should not make any difference

**Comment by SalahAdDin** [comment]
So, why are they not working? it is a interesting thing, should i remove the cache?

**Comment by mohamedmagdy** [comment]
If you already did `Invalidate Caches / Restart`, then the cache is already removed

**Comment by SalahAdDin** [comment]
I did two times, just restart. Now i tried with `Invalidate and Restart`.
It does not work. I used the first method.
