### ISSUE TITLE
Error: Load Settings

### ISSUE THREAD

**Issue by heshamfm** [mohamedmagdy/odoo-pycharm-templates#2]
Saves the odoo.xml file in the templates directory. But when  Itry to edit an exisitng .xml file it gives the following error:

`Load Settings
Cannot read scheme Odoo.xml  from '$ROOT_CONFIG$/templates': Error on line 34: Attribute name "data-pjax-transient" associated with an element type "meta" must be followed by the ' = ' character.`

**Comment by mohamedmagdy** [comment]
You do not have to Edit the file manually, You can find the 'live templates' in PyCharm Under settings.

You can edit it from there :)

**Comment by heshamfm** [comment]
True. I did something very simple. I copied and pasted the content of `Odoo.xml` into a fresh file within PyCharm and Saved-As to the target folder. That made the file have the required ownership and permission info.
