### ISSUE TITLE
Unable to install with Pycharm Community Edition 2016.1

### ISSUE THREAD

**Issue by Motez** [mohamedmagdy/odoo-pycharm-templates#5]
Thank you Mohamed for the tool ! 
I can't install the template as there is no templates folder for my Pycharm Community Edition 2016.1

**Comment by JosDeGraeve** [comment]
Hi,

Fwiw, on Mac OS X with 2016.1 the templates are located here:
`~/Library/Preferences/PyCharm2016.1/templates`

@Motez what os are you using ?

**Comment by Motez** [comment]
I'am using Ubuntu 15.10 .

**Comment by JosDeGraeve** [comment]
Hi,

This should get you started:
https://www.jetbrains.com/help/pycharm/2016.1/directories-used-by-pycharm-to-store-settings-caches-plugins-and-logs.html?origin=old_help
